plugins {
	id 'java-library'
	id 'maven-publish'
	id 'eclipse'
	id 'org.jetbrains.gradle.plugin.idea-ext' version '1.3'
	id 'com.gtnewhorizons.retrofuturagradle' version '2.0.2'
}

group = 'kaduvill.xnetadditions'
version = '0.2.2_ALPHA'

if (System.getenv('BUILD_NUMBER') != null) {
	version = "${version}.${System.getenv('BUILD_NUMBER')}"
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	sourceCompatibility = '1.8'
	targetCompatibility = '1.8'
	options.release.set(8)

	javaCompiler.set(javaToolchains.compilerFor {
		languageVersion.set(JavaLanguageVersion.of(17))
		vendor.set(JvmVendorSpec.AZUL)
	})
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

minecraft {
	mcVersion.set('1.12.2')
	useDependencyAccessTransformers.set(true)
	username.set('Developer')

	extraRunJvmArguments.add("-ea:${project.group}")
	extraRunJvmArguments.add('-Dmixin.checks.interfaces=true')

	tagReplacementFiles.add("XNetAdditions.java")
	injectedTags.put("GRADLETOKEN_VERSION", project.version.toString())
}

repositories {
	mavenCentral()

	maven { url = uri('https://cursemaven.com') }
	maven { url = uri('https://maven.cil.li') }
	maven { url = uri('https://nexus.gtnewhorizons.com/repository/public/') }
	maven { url = uri('https://maven.cleanroommc.com') }
	maven { url = uri('https://repo.spongepowered.org/maven') }

	flatDir {
		dirs 'libs'
	}
}


sourceSets {
	main {
		resources {
			srcDirs += 'docs'
		}
	}
}

configurations {
	localRuntime
	runtimeClasspath.extendsFrom(localRuntime)
}

dependencies {
	String mixinBooter = modUtils.enableMixins(
			'zone.rong:mixinbooter:10.7',
			'xnetadditions.refmap.json'
	)
	api(mixinBooter) {
		transitive = false
	}
	annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
	annotationProcessor 'com.google.guava:guava:32.1.2-jre'
	annotationProcessor 'com.google.code.gson:gson:2.8.9'
	annotationProcessor(mixinBooter) {
		transitive = false
	}

	//local dirty latest
	implementation files("libs/XNet-1.8.23-dev.jar")
	//implementation rfg.deobf("curse.maven:znet-1335763:8438514")
	implementation rfg.deobf("curse.maven:mcjtylib-233105:2745846")

	// TOP
	compileOnly(rfg.deobf("curse.maven:the-one-probe-245211:2667280")) {transitive = false}
	//localRuntime(rfg.deobf("curse.maven:the-one-probe-245211:2667280")) {transitive = false}

	// HEI versions

	// 4.31.2
	compileOnly(rfg.deobf("curse.maven:had-enough-items-557549:8081514")) // 4.31.2
	localRuntime(rfg.deobf("curse.maven:had-enough-items-557549:8081514")) // 4.31.2

	// 4.34.0
	//compileOnly(rfg.deobf("curse.maven:had-enough-items-557549:8576621")) {transitive = false}
	//localRuntime(rfg.deobf("curse.maven:had-enough-items-557549:8576621")) {transitive = false}


	//implementation("curse.maven:jei-238222:5846804") // JEI 4.16.1.1013
	//implementation("curse.maven:had-enough-items-557549:4810661") // 4.25.1
	//implementation("curse.maven:had-enough-items-557549:8081514") // 4.31.2


	// JEI-Utilities
	localRuntime(rfg.deobf("curse.maven:jei-utilities-616190:8528497")) {transitive = false}



	compileOnly rfg.deobf("curse.maven:tesla-244651:2487959")
	compileOnly rfg.deobf("curse.maven:industrial-craft-242638:3838715")
	compileOnly rfg.deobf("curse.maven:thaumcraft-223628:2629023")
	compileOnly rfg.deobf("curse.maven:mekanism-268560:2835176")
	compileOnly rfg.deobf("curse.maven:botania-225643:3330934")
	compileOnly rfg.deobf("curse.maven:flux-networks-248020:3174795")
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'mcversion', minecraft.mcVersion.get()

	filesMatching('mcmod.info') { fcd ->
		fcd.expand(
				'version': project.version,
				'mcversion': minecraft.mcVersion.get()
		)
	}
}

publishing {
	publications {
		maven(MavenPublication) {
			from components.java
		}
	}
}

idea {
	module {
		downloadJavadoc = true
		downloadSources = true
		inheritOutputDirs = true
	}
}